### ISSUE TITLE
Tepe does not run on Ubuntu 20.04-LTS desktop 

### ISSUE THREAD

**Issue by ShabbirHasan1** [Hermitter/tepe#4]
**Describe the bug**
It seems tepe need higher version of glibc 2.32 than Ubuntu 20.04-LTS (2.31)

```
 $  ./tepe
 $  ./tepe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./tepe)

 $ sudo apt install libc6                                              
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    libc6 is already the newest version (2.31-0ubuntu9.2).
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 $ ldd --version
    ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
    Copyright (C) 2020 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    Written by Roland McGrath and Ulrich Drepper.
```

**Comment by Hermitter** [comment]
I'll update the CI to create [fully static binaries](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html) soon to fix this issue.

**Comment by ShabbirHasan1** [comment]
> I'll update the CI to create [fully static binaries](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html) soon to fix this issue.

Thanks for the update Hope to see the new release with fully static binaries soon to download..

**Comment by Hermitter** [comment]
Binaries are now prebuilt for `x86_64` Linux, Windows, and macOS.

https://github.com/Hermitter/tepe/releases/tag/v0.0.5
